import Link from "next/link";
import "../styles/globals.css";
import IntroduceMenu from "@/components/IntroduceMenu";

export const metadata = {
  title: "Song`s Blog",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const header = (
    <header>
      <div className="text-center bg-slate-700 p-8 mt-6 rounded-md">
        <div className="group relative mt-4 mb-3 flex justify-center">
          <h1 className="text-2xl text-white font-bold ">Song's Blog</h1>
          <span className="absolute top-10 scale-0 transition-all rounded bg-gray-800 p-2 text-left text-xs text-white group-hover:scale-100">
            ✨ 7년차 WEB 개발자
            <br />✨ 3년차 Front-end 개발자
            <br />✨ (주)알티모빌리티 근무 중
            <br />✨ 이 Blog Web은 NextJS/Typescript 와 TailwindCSS 로 구성되어
            있습니다.
          </span>
        </div>
        <p className="text-slate-300 text-xs sm:text-sm">
          송찬흠의 Dev Blog 입니다! (2021-08 ~ 진행중)
        </p>
      </div>
      <IntroduceMenu />
    </header>
  );
  const footer = (
    <footer>
      <div className="border-t border-slate-400 mt-8 py-6 text-center text-slate-400">
        <h3>Developed by Chanheum Song</h3>
      </div>
    </footer>
  );
  return (
    <html lang="en">
      <body>
        <div className="mx-auto md:max-w-2xl lg:max-w-4xl px-6">
          {header}
          {children}
          {footer}
        </div>
      </body>
    </html>
  );
}
