import Link from "next/link";

export const metadata = {
  title: "Song`s Blog",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const header = (
    <header>
      <div>
        <Link href={`/`}>
          <h1>Song's Blog</h1>
        </Link>
      </div>
    </header>
  );
  return (
    <html lang="en">
      <body>
        {header}
        {children}
      </body>
    </html>
  );
}
